trigger:
- main

variables:
  tag: '$(Build.BuildId)'
  dockerfilePath: '$(Build.SourcesDirectory)/dockerfile'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(dockerfilePath)'
        tags: |
          $(tag)

- stage: Test
  displayName: Test
  jobs:
  - job: Test
    displayName: Run tests
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        # Thay thế bằng lệnh test thực tế của bạn
        echo "Running tests..."
        # Ví dụ: npm test

- stage: Deploy
  displayName: Deploy to production
  jobs:
  - deployment: Deploy
    displayName: Deploy app
    pool:
      vmImage: ubuntu-latest
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              # Thay thế bằng lệnh deploy thực tế của bạn
              echo "Deploying application..."
              # Ví dụ: kubectl apply -f deployment.yaml