trigger:
- main

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo "Build stage passed"

- stage: Test
  jobs:
  - job: Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo "Test stage passed"

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: echo "Deploy stage passed"