trigger:
- main

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Simulating Docker build process..."
        echo "Docker image built successfully with tag: $(tag)"

- stage: Test
  displayName: Test
  jobs:
  - job: Test
    displayName: Run tests
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: |
        echo "Simulating test execution..."
        echo "All tests passed successfully!"

- stage: Deploy
  displayName: Deploy to production
  jobs:
  - deployment: Deploy
    displayName: Deploy app
    pool:
      vmImage: ubuntu-latest
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Simulating deployment process..."
              echo "Application deployed successfully to production!"